# Generated by Django 6.1 on 2026-08-10 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='coconuts/images/%Y/%m/%d/')),
                ('audio_file', models.FileField(upload_to='coconuts/audio/%Y/%m/%d/')),
                ('visual_prediction', models.CharField(choices=[('Premature', 'Premature'), ('Mature', 'Mature'), ('Overmature', 'Overmature')], max_length=20)),
                ('audio_prediction', models.CharField(choices=[('Premature', 'Premature'), ('Mature', 'Mature'), ('Overmature', 'Overmature')], max_length=20)),
                ('final_maturity_stage', models.CharField(choices=[('Premature', 'Premature'), ('Mature', 'Mature'), ('Overmature', 'Overmature')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('is_synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
